### ISSUE TITLE
Default audience string missing https

### ISSUE THREAD

**Issue by junying1** [chris-garrett/garrett-streamlit-auth0#14]
Hi,

Thank you for forking and updating this repo. It's extremely helpful. I noticed that the default audience is constructed as f"{domain}/api/v2". It should be f"https://{domain}/api/v2", if is not overiden in the login_button constructor. It might be helpful to also add example setting the audience in the constructor.

I'm happy to fork and PR, but thought it's probably faster if you just did it.

Thank you.

**Comment by chris-garrett** [comment]
> It should be f"https://{domain}/api/v2"

good catch, ill update that. 

> It might be helpful to also add example setting the audience in the constructor.

agreed. tbh, i didnt expect anyone to use this package. at least, not right away. i havent spent any time on docs or cleaning up the code since im hyper-focused on getting this working in a few production apps.

**Comment by chris-garrett** [comment]
hi @junying1, can you give `0.6` a try please?

**Comment by junying1** [comment]
I sure will. Thank you for the quick fix. Yeah I know you were just forking it to continue your development. I appreciate it.

Seems it has some peculiar behaviors on mobile. I'm working through it. I'll let you know when I figure it out. If you want to add me as a collaborator, I'll be happy to contribute PR's. Just want to avoid another fork.

Thanks again.

**Comment by junying1** [comment]
All good. Thank you.
